apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - develop
jobs:
  ci-job:
    outputs:
      image_tag: ${{ steps.step1.outputs.current_datetime }}
    steps:
      - name: derive_image_id
        uses: docker://bash:5
        shell: bash
        run: date '+%Y%m%d%H%M%S' > "$CLOUDBEES_OUTPUTS/current_datetime"
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - uses: docker://maven:3.9.3-amazoncorretto-17
        name: Run Build With Tests
        run: |
          mvn clean install
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        name: Sonar scan
        kind: scan
        with:
          language: JAVA
      - name: Set up Docker Hub registry
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: index.docker.io # or docker.io
          username: ${{ vars.QUICKSTART_DOCKER_USERNAME }}
          password: ${{ secrets.QUICKSTART_DOCKER_PASSWORD }}
      - name: Generate timestamp
        id: timestamp # This will hold the output of the step, in this case, the timestamp
        run: echo "::set-output name=TIMESTAMP::$(date '+%Y%m%d%H%M%S')"
        uses: docker://bash:5
      - name: Push image to registry
        uses: cloudbees-io/kaniko@v1
        with:
            destination: ${{ vars.QUICKSTART_DOCKER_USERNAME }}/trainticket:${{ steps.timestamp.outputs.TIMESTAMP }}
