apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    steps:
      - name: Run Tests
        uses: docker://maven:3.9.3-amazoncorretto-17
        shell: sh
        run: |
          mvn test
