apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - develop
jobs:
  ci-job:
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - uses: docker://maven:3.9.3-amazoncorretto-17
        name: Run Tests
        run: |
          mvn test
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        name: Sonar scan
        kind: scan
        with:
          language: JAVA
